export const CREATECONTACT = 'CREATECONTACT';
export const CREATECONTACTSUCCESS = 'CREATECONTACTSUCCESS';
export const CREATECONTACTFAILURE = 'CREATECONATCTFAILURE';
export const GETCONTACTLIST = 'GETCONTACTLIST';
export const GETCONTACTLISTSUCCESS = 'GETCONTACTLISTSUCCESS';
export const GETCONTACTLISTFAILURE = 'GETCONTACTLISTFAILURE';
export const FIRSTNAMECHANGE = 'FIRSTNAMECHANGE';
export const LASTNAMECHANGE = 'LASTNAMECHANGE';
export const PHONENUMBERCHANGE = 'PHONENUMBERCHANGE';
export const ALTERNATENUMBERCHANGE = 'ALTERNATENUMBERCHANGE';
export const EMAILCHANGE = 'EMAILCHANGE';
export const ADDRESSCHANGE = 'ADDRESSCHANGE';
export const SEARCHTEXTCHANGE = 'SEARCHTEXTCHANGE';
export const SEARCHTEXT = 'SEARCHTEXT';
export const SEARCHTEXTSUCCESS = 'SEARCHTEXTSUCCESS';
export const SEARCHTEXTFAILURE = 'SEARCHTEXTFAILURE';
export const CLEAR = 'CLEAR';

